---
 - name: "在centos上安装nginx"
   yum: name=nginx  state=latest
   tags: nginx
 - name: "修改服务器上nginx的配置文件nginx.conf"
   template: src="templates/nginx.conf.j2" dest="/etc/nginx/nginx.conf"
   notify:
     - restart nginx
 - name: "修改服务器上host为cakechina.org的配置文件"
   template: src="templates/nginx_vhost.j2" dest="/etc/nginx/default.d/www.cakechina.org.conf"
   notify:
     - restart nginx
